### ISSUE TITLE
Use group id 'market.hytale.rest' instead of 'market.hytale'

### ISSUE THREAD

**Issue by shadowcoree** [HytaleMarket/hytale-web-api-client-java#2]
## Issue
To be honest, `market.hytale` is a bit _too_ general. There are certainly gonna be more projects which are related with Hytale and the Hytale Marketplace itself and the group id `market.hytale.rest` would fit a lot better. Another reason would be: I wouldn't have to read this ass long artifact id _hytale-web-api-client-java_ just to find out: Aight, that's a API you can do web/rest stuff with.

## Proposed change
Before:
```xml
<groupId>market.hytale</groupId>
<artifactId>hytale-web-api-client-java</artifactId>
<version>1.0.0</version>
<packaging>jar</packaging>
```
After:
```xml
<groupId>market.hytale.rest</groupId>
<artifactId>hytale-web-api-client-java</artifactId>
<version>1.0.0</version>
<packaging>jar</packaging>
```

**Comment by Krymonota** [comment]
Changed in https://github.com/HytaleMarket/hytale-web-api-client-java/commit/d4985234d06e85b074f6a9b2517ba10df45f87cd.
